name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
        scope: '@EricssonBroadcastServices'
    - name: install
      run: npm ci
    - name: build
      run: npm run build
    - name: test
      run: npm run test
    - name: lint
      run: npm run lint
